Repository 0ne6yte/life-4-cut-frontend, pull requests merged in 2023-09, with the labels that each got.

#27 fix: prettier import sort 오류 및 버전 호환성 오류 해결
  .prettierrc.js
  .yarnrc.yml
  README.md
  package.json
  src/App.tsx
  src/domain/_common/components/input.css
  src/domain/_common/styles/global.css
  src/routers/AlbumRouters.tsx
  src/routers/PhotoRouters.tsx
  src/stories/Configure.mdx
  yarn.lock
Labels: Fix ⚒️, Config ⚙️

#30 [REFACTOR]: Px -> Rem으로 config 변경
  tailwind.config.js
  vite.config.js
Labels: Config ⚙️

#31 Feature/integrate tailwind storybook
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/routers/AlbumRouters.tsx
  src/routers/PhotoRouters.tsx
  yarn.lock
Labels: 긴급 🚨, 중요도: 중 😌, Config ⚙️

#35 react-hook-form & yup 적용
  .eslintrc.js
  package.json
  src/domain/_common/components/Input.tsx
  src/domain/_common/components/TextInput.tsx
  src/domain/_common/components/index.ts
  src/domain/_common/components/textInput.css
  src/domain/_common/hooks/index.ts
  src/domain/_common/hooks/useForm.ts
  src/stories/Input.stories.ts
  src/stories/TextInput.stories.tsx
  src/utils/validation.ts
  tailwind.config.ts
  tsconfig.json
  vite.config.js
  yarn.lock
Labels: Feature 🎡

#32 Feature/storybook button component
  .eslintignore
  .storybook/main.ts
  package.json
  src/domain/_common/components/Button.tsx
  src/domain/_common/components/index.ts
  src/stories/button.stories.ts
  tailwind.config.ts
  yarn.lock
Labels: Feature 🎡, 중요도: 중 😌

#34 FloatingButton 컴포넌트 구현
  src/assets/plus.svg
  src/domain/_common/components/FloatingButton.tsx
  src/domain/_common/components/index.ts
  src/stories/FloatingButton.stories.tsx
  tailwind.config.ts
  yarn.lock
Labels: Feature 🎡
