Repository 0ne6yte/life-4-cut-frontend, pull requests merged in 2023-10, with the labels that each got.

#38 TextInput component style tailwind 적용, convention 수정
  .storybook/preview.ts
  .yarn/releases/yarn-3.6.1.cjs
  README.md
  index.html
  package.json
  src/App.tsx
  src/Main.tsx
  src/domain/Album/AlbumList/index.tsx
  src/domain/Album/EditAlbum/index.tsx
  src/domain/Album/RegisterAlbum/index.tsx
  src/domain/Login/index.tsx
  src/domain/MyPage/index.tsx
  src/domain/Photo/PhotoList/index.tsx
  src/domain/Photo/RegisterPhoto/index.tsx
  src/domain/_common/components/Button.tsx
  src/domain/_common/components/FloatingButton.tsx
  src/domain/_common/components/TextInput.tsx
  src/domain/_common/components/textInput.css
  src/domain/login/components/index.tsx
  src/domain/login/hooks/index.ts
  src/domain/login/index.tsx
  src/domain/myPage/components/index.tsx
  src/domain/myPage/hooks/index.ts
  src/domain/myPage/index.tsx
  src/global.css
  src/hooks/index.ts
  src/hooks/useForm.ts
  src/stories/TextInput.stories.tsx
Labels: Docs 📋, Feature 🎡, Config ⚙️

#39 Badge Component 생성
  src/assets/user.svg
  src/domain/Album/EditAlbum/hooks/index.ts
  src/domain/Album/RegisterAlbum/components/index.tsx
  src/domain/Album/RegisterAlbum/hooks/index.ts
  src/domain/Photo/PhotoList/components/index.tsx
  src/domain/Photo/PhotoList/hooks/index.ts
  src/domain/Photo/RegisterPhoto/components/index.tsx
  src/domain/Photo/RegisterPhoto/hooks/index.ts
  src/domain/_common/components/Badge.tsx
  src/domain/album/AlbumList/components/index.tsx
  src/domain/album/AlbumList/index.tsx
  src/domain/album/EditAlbum/components/index.tsx
  src/domain/album/EditAlbum/index.tsx
  src/domain/album/RegisterAlbum/components/index.tsx
  src/domain/album/RegisterAlbum/index.tsx
  src/domain/photo/PhotoList/components/index.tsx
  src/domain/photo/PhotoList/index.tsx
  src/domain/photo/RegisterPhoto/components/index.tsx
  src/domain/photo/RegisterPhoto/index.tsx
  src/routers/AlbumRouters.tsx
  src/routers/PhotoRouters.tsx
  src/stories/Badge.stories.tsx
  tailwind.config.ts
Labels: Feature 🎡

#43 IconButton 컴포넌트 구현
  src/assets/arrow-down.svg
  src/domain/_common/components/IconButton.tsx
  src/domain/_common/components/index.ts
  src/stories/IconButton.stories.tsx
Labels: Feature 🎡

#46 feat: Badge -> Tag/Chip 으로 분리
  src/domain/_common/components/Badge.tsx
  src/domain/_common/components/Chip.tsx
  src/domain/_common/components/Tag.tsx
  src/stories/Badge.stories.tsx
  src/stories/Chip.stories.tsx
  src/stories/Tag.stories.tsx
Labels: Feature 🎡

#45 Stepper Component 구현
  src/domain/_common/components/Stepper.tsx
  src/domain/_common/components/index.ts
  src/stories/Stepper.stories.tsx
Labels: Feature 🎡

#49 [Feat] thumnail component 개발
  src/assets/member-mark.svg
  src/assets/vertical-ellipsis.svg
  src/domain/_common/components/AlbumThumbnail/index.tsx
  src/stories/AlbumTumbnail.stories.tsx
Labels: Feature 🎡

#53 Button 컴포넌트 리팩토링
  .DS_Store
  src/domain/_common/components/Badge.tsx
  src/domain/_common/components/Button.tsx
  src/domain/album/AlbumList/hooks/index.ts
  src/domain/album/EditAlbum/hooks/index.ts
  src/domain/album/RegisterAlbum/hooks/index.ts
  src/domain/photo/PhotoList/hooks/index.ts
  src/domain/photo/RegisterPhoto/hooks/index.ts
  src/stories/Badge.stories.tsx
  src/stories/Button.stories.ts
  src/stories/TextInput.stories.tsx
Labels: Refactor 🌈, 중요도: 중 😌

#50 [Feat]안내 bubble 컴포넌트 제작
  src/domain/_common/components/Bubble/index.tsx
  src/domain/_common/components/index.ts
  src/stories/Bubble.stories.tsx
Labels: Feature 🎡

#55 Dropdown 컴포넌트 개발
  src/domain/_common/components/Dropdown.tsx
  src/domain/_common/components/index.ts
  src/stories/Dropdown.stories.tsx
Labels: Feature 🎡

#52 Tab 컴포넌트 구현
  src/assets/camera.svg
  src/assets/picture.svg
  src/assets/qr.svg
  src/domain/_common/components/Tab.tsx
  src/domain/_common/components/index.ts
  src/stories/Tab.stories.tsx
Labels: Feature 🎡

#56 feat: Button style variant, color로 분기
  src/domain/_common/components/Button.tsx
  src/stories/Button.stories.ts
  src/stories/Button.stories.tsx
  src/stories/TextInput.stories.tsx
Labels: Feature 🎡

#59 feat: 레이아웃 패딩 추가 및 모바일 개발을 위한 배경색 추가
  src/domain/_common/layouts/DefaultMobileLayout/index.tsx
  src/global.css
Labels: Feature 🎡

#48 [Feat]Avatar 컴포넌트 개발
  src/assets/avatar-icon.svg
  src/assets/x-button.svg
  src/domain/_common/components/Avatar.tsx
  src/domain/_common/components/index.ts
  src/stories/Avatar.stories.tsx
  src/utils/generateVividColor.ts
  src/utils/index.ts
  src/utils/pxToRem.ts
  vite.config.ts
  yarn.lock
Labels: Feature 🎡
